services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    container_name: inout_central_db
    ports:
      - "127.0.0.1:${POSTGRES_HOST_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: inout_central
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
