// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/funil-crm/DonutCards.tsx": () => import("../components/mockups/funil-crm/DonutCards.tsx"),
  "./components/mockups/funil-crm/GradientBars.tsx": () => import("../components/mockups/funil-crm/GradientBars.tsx")
};
